
# https://manski.net/2016/09/vagrant-multi-machine-tutorial/

NODE_COUNT = 1

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.define "master" do |node|
    node.vm.hostname = "master.cloudyx.site"
    node.vm.network :private_network, ip: "10.0.0.10"
    node.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
    node.vm.provision "shell", path: "bootstrap.sh"
    node.vm.provision "shell", path: "freeipa-server.sh"
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}.cloudyx.site"
      node.vm.network :private_network, ip: "10.0.0.#{i + 10}"
      node.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
      end
      node.vm.provision "shell", path: "bootstrap.sh"
    end
  end
  
end
