# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "boxcutter/centos71"

  config.vm.network "private_network", ip: "10.0.90.11"

  if Vagrant.has_plugin?("vagrant-cachier")
      config.cache.scope = :box
  end

  #config.vm.provision "shell", path: "bootstrap_btrfs.sh"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]

    (1..5).each do |i|
       storage_disk = "c7_storage_disk#{i}.vdi"
       unless File.exist?(storage_disk)
          vb.customize ["createhd",  "--filename", storage_disk, "--size", "4096"]
       end
       vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", "#{i}", "--type", "hdd", "--medium", storage_disk]
    end

  end

end
