# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "fedora-22-server"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    #vb.customize ["storagectl", :id, "--name", "SATA Controller", "--add", "sata"]

    (1..4).each do |i|
       vb.customize ["createhd",  "--filename", "btrfs_disk#{i}", "--size", "2048"]
       vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", "#{i}", "--type", "hdd", "--medium", "btrfs_disk#{i}.vdi"]
    end

  end

end
