# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "akanto/fedora-23-server"

#  config.vm.box = "boxcutter/centos71"

#  if Vagrant.has_plugin?("vagrant-cachier")
#      config.cache.scope = :box
  #end

  (0..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"
      node.vm.network "private_network", ip: "10.0.0.1#{i}"
      # Configure networking for advanced topics
      node.vm.network "public_network", bridge: "en3: Thunderbolt Ethernet"
      node.vm.provision "shell", inline: "route del default && route add default gw 192.168.1.1 enp0s9"
      node.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
          vb.customize ["modifyvm", :id, "--memory", "1024"]
          vb.customize ["modifyvm", :id, "--cpus", "1"]
      end
      node.vm.provision "shell", path: "bootstrap_docker.sh"
    end
  end
  # does not work with dnf
  #if Vagrant.has_plugin?("vagrant-cachier")
  #    config.cache.scope = :box
  #end



end
